QUALIMAP=~/Downloads/qualimap_v1.0/qualimap
mkdir ../coverage_et_qual

$QUALIMAP bamqc -bam ../bams/IonXpress_001_rawlib.bam -outdir ../coverage_et_qual/001
$QUALIMAP bamqc -bam ../bams/IonXpress_002_rawlib.bam -outdir ../coverage_et_qual/002
$QUALIMAP bamqc -bam ../bams/IonXpress_003_rawlib.bam -outdir ../coverage_et_qual/003
$QUALIMAP bamqc -bam ../bams/IonXpress_004_rawlib.bam -outdir ../coverage_et_qual/004
$QUALIMAP bamqc -bam ../bams/IonXpress_005_rawlib.bam -outdir ../coverage_et_qual/005
$QUALIMAP bamqc -bam ../bams/IonXpress_006_rawlib.bam -outdir ../coverage_et_qual/006
$QUALIMAP bamqc -bam ../bams/IonXpress_007_rawlib.bam -outdir ../coverage_et_qual/007
$QUALIMAP bamqc -bam ../bams/IonXpress_008_rawlib.bam -outdir ../coverage_et_qual/008
$QUALIMAP bamqc -bam ../bams/IonXpress_009_rawlib.bam -outdir ../coverage_et_qual/009
$QUALIMAP bamqc -bam ../bams/IonXpress_010_rawlib.bam -outdir ../coverage_et_qual/010
$QUALIMAP bamqc -bam ../bams/IonXpress_011_rawlib.bam -outdir ../coverage_et_qual/011
$QUALIMAP bamqc -bam ../bams/IonXpress_012_rawlib.bam -outdir ../coverage_et_qual/012
$QUALIMAP bamqc -bam ../bams/IonXpress_013_rawlib.bam -outdir ../coverage_et_qual/013
$QUALIMAP bamqc -bam ../bams/IonXpress_014_rawlib.bam -outdir ../coverage_et_qual/014
$QUALIMAP bamqc -bam ../bams/IonXpress_015_rawlib.bam -outdir ../coverage_et_qual/015
$QUALIMAP bamqc -bam ../bams/IonXpress_016_rawlib.bam -outdir ../coverage_et_qual/016
$QUALIMAP bamqc -bam ../bams/IonXpress_017_rawlib.bam -outdir ../coverage_et_qual/017
$QUALIMAP bamqc -bam ../bams/IonXpress_018_rawlib.bam -outdir ../coverage_et_qual/018
$QUALIMAP bamqc -bam ../bams/IonXpress_019_rawlib.bam -outdir ../coverage_et_qual/019
$QUALIMAP bamqc -bam ../bams/IonXpress_020_rawlib.bam -outdir ../coverage_et_qual/020
$QUALIMAP bamqc -bam ../bams/IonXpress_021_rawlib.bam -outdir ../coverage_et_qual/021
$QUALIMAP bamqc -bam ../bams/IonXpress_022_rawlib.bam -outdir ../coverage_et_qual/022
$QUALIMAP bamqc -bam ../bams/IonXpress_023_rawlib.bam -outdir ../coverage_et_qual/023
$QUALIMAP bamqc -bam ../bams/IonXpress_024_rawlib.bam -outdir ../coverage_et_qual/024
$QUALIMAP bamqc -bam ../bams/IonXpress_025_rawlib.bam -outdir ../coverage_et_qual/025
$QUALIMAP bamqc -bam ../bams/IonXpress_026_rawlib.bam -outdir ../coverage_et_qual/026
$QUALIMAP bamqc -bam ../bams/IonXpress_027_rawlib.bam -outdir ../coverage_et_qual/027
$QUALIMAP bamqc -bam ../bams/IonXpress_028_rawlib.bam -outdir ../coverage_et_qual/028
$QUALIMAP bamqc -bam ../bams/IonXpress_029_rawlib.bam -outdir ../coverage_et_qual/029
$QUALIMAP bamqc -bam ../bams/IonXpress_030_rawlib.bam -outdir ../coverage_et_qual/030
$QUALIMAP bamqc -bam ../bams/IonXpress_031_rawlib.bam -outdir ../coverage_et_qual/031
$QUALIMAP bamqc -bam ../bams/IonXpress_032_rawlib.bam -outdir ../coverage_et_qual/032
$QUALIMAP bamqc -bam ../bams/IonXpress_033_rawlib.bam -outdir ../coverage_et_qual/033
$QUALIMAP bamqc -bam ../bams/IonXpress_034_rawlib.bam -outdir ../coverage_et_qual/034
$QUALIMAP bamqc -bam ../bams/IonXpress_035_rawlib.bam -outdir ../coverage_et_qual/035
$QUALIMAP bamqc -bam ../bams/IonXpress_036_rawlib.bam -outdir ../coverage_et_qual/036
$QUALIMAP bamqc -bam ../bams/IonXpress_037_rawlib.bam -outdir ../coverage_et_qual/037
$QUALIMAP bamqc -bam ../bams/IonXpress_038_rawlib.bam -outdir ../coverage_et_qual/038
$QUALIMAP bamqc -bam ../bams/IonXpress_039_rawlib.bam -outdir ../coverage_et_qual/039
$QUALIMAP bamqc -bam ../bams/IonXpress_040_rawlib.bam -outdir ../coverage_et_qual/040
$QUALIMAP bamqc -bam ../bams/IonXpress_041_rawlib.bam -outdir ../coverage_et_qual/041
$QUALIMAP bamqc -bam ../bams/IonXpress_042_rawlib.bam -outdir ../coverage_et_qual/042
$QUALIMAP bamqc -bam ../bams/IonXpress_043_rawlib.bam -outdir ../coverage_et_qual/043
$QUALIMAP bamqc -bam ../bams/IonXpress_044_rawlib.bam -outdir ../coverage_et_qual/044
$QUALIMAP bamqc -bam ../bams/IonXpress_045_rawlib.bam -outdir ../coverage_et_qual/045
$QUALIMAP bamqc -bam ../bams/IonXpress_046_rawlib.bam -outdir ../coverage_et_qual/046
$QUALIMAP bamqc -bam ../bams/IonXpress_047_rawlib.bam -outdir ../coverage_et_qual/047
$QUALIMAP bamqc -bam ../bams/IonXpress_048_rawlib.bam -outdir ../coverage_et_qual/048
$QUALIMAP bamqc -bam ../bams/IonXpress_049_rawlib.bam -outdir ../coverage_et_qual/049
$QUALIMAP bamqc -bam ../bams/IonXpress_050_rawlib.bam -outdir ../coverage_et_qual/050
$QUALIMAP bamqc -bam ../bams/IonXpress_051_rawlib.bam -outdir ../coverage_et_qual/051
$QUALIMAP bamqc -bam ../bams/IonXpress_052_rawlib.bam -outdir ../coverage_et_qual/052
$QUALIMAP bamqc -bam ../bams/IonXpress_053_rawlib.bam -outdir ../coverage_et_qual/053
$QUALIMAP bamqc -bam ../bams/IonXpress_054_rawlib.bam -outdir ../coverage_et_qual/054
$QUALIMAP bamqc -bam ../bams/IonXpress_055_rawlib.bam -outdir ../coverage_et_qual/055
$QUALIMAP bamqc -bam ../bams/IonXpress_056_rawlib.bam -outdir ../coverage_et_qual/056
$QUALIMAP bamqc -bam ../bams/IonXpress_057_rawlib.bam -outdir ../coverage_et_qual/057
$QUALIMAP bamqc -bam ../bams/IonXpress_058_rawlib.bam -outdir ../coverage_et_qual/058
$QUALIMAP bamqc -bam ../bams/IonXpress_059_rawlib.bam -outdir ../coverage_et_qual/059
$QUALIMAP bamqc -bam ../bams/IonXpress_060_rawlib.bam -outdir ../coverage_et_qual/060
$QUALIMAP bamqc -bam ../bams/IonXpress_061_rawlib.bam -outdir ../coverage_et_qual/061
$QUALIMAP bamqc -bam ../bams/IonXpress_062_rawlib.bam -outdir ../coverage_et_qual/062
$QUALIMAP bamqc -bam ../bams/IonXpress_063_rawlib.bam -outdir ../coverage_et_qual/063
$QUALIMAP bamqc -bam ../bams/IonXpress_064_rawlib.bam -outdir ../coverage_et_qual/064
$QUALIMAP bamqc -bam ../bams/IonXpress_065_rawlib.bam -outdir ../coverage_et_qual/065
$QUALIMAP bamqc -bam ../bams/IonXpress_066_rawlib.bam -outdir ../coverage_et_qual/066
$QUALIMAP bamqc -bam ../bams/IonXpress_067_rawlib.bam -outdir ../coverage_et_qual/067
$QUALIMAP bamqc -bam ../bams/IonXpress_068_rawlib.bam -outdir ../coverage_et_qual/068
$QUALIMAP bamqc -bam ../bams/IonXpress_069_rawlib.bam -outdir ../coverage_et_qual/069
$QUALIMAP bamqc -bam ../bams/IonXpress_070_rawlib.bam -outdir ../coverage_et_qual/070
$QUALIMAP bamqc -bam ../bams/IonXpress_071_rawlib.bam -outdir ../coverage_et_qual/071
$QUALIMAP bamqc -bam ../bams/IonXpress_072_rawlib.bam -outdir ../coverage_et_qual/072
$QUALIMAP bamqc -bam ../bams/IonXpress_073_rawlib.bam -outdir ../coverage_et_qual/073
$QUALIMAP bamqc -bam ../bams/IonXpress_074_rawlib.bam -outdir ../coverage_et_qual/074
$QUALIMAP bamqc -bam ../bams/IonXpress_075_rawlib.bam -outdir ../coverage_et_qual/075
$QUALIMAP bamqc -bam ../bams/IonXpress_076_rawlib.bam -outdir ../coverage_et_qual/076
$QUALIMAP bamqc -bam ../bams/IonXpress_077_rawlib.bam -outdir ../coverage_et_qual/077
$QUALIMAP bamqc -bam ../bams/IonXpress_078_rawlib.bam -outdir ../coverage_et_qual/078
$QUALIMAP bamqc -bam ../bams/IonXpress_079_rawlib.bam -outdir ../coverage_et_qual/079
$QUALIMAP bamqc -bam ../bams/IonXpress_080_rawlib.bam -outdir ../coverage_et_qual/080
$QUALIMAP bamqc -bam ../bams/IonXpress_081_rawlib.bam -outdir ../coverage_et_qual/081
$QUALIMAP bamqc -bam ../bams/IonXpress_082_rawlib.bam -outdir ../coverage_et_qual/082
$QUALIMAP bamqc -bam ../bams/IonXpress_083_rawlib.bam -outdir ../coverage_et_qual/083
$QUALIMAP bamqc -bam ../bams/IonXpress_084_rawlib.bam -outdir ../coverage_et_qual/084
$QUALIMAP bamqc -bam ../bams/IonXpress_085_rawlib.bam -outdir ../coverage_et_qual/085
$QUALIMAP bamqc -bam ../bams/IonXpress_086_rawlib.bam -outdir ../coverage_et_qual/086
$QUALIMAP bamqc -bam ../bams/IonXpress_087_rawlib.bam -outdir ../coverage_et_qual/087
$QUALIMAP bamqc -bam ../bams/IonXpress_088_rawlib.bam -outdir ../coverage_et_qual/088
$QUALIMAP bamqc -bam ../bams/IonXpress_089_rawlib.bam -outdir ../coverage_et_qual/089
$QUALIMAP bamqc -bam ../bams/IonXpress_090_rawlib.bam -outdir ../coverage_et_qual/090
$QUALIMAP bamqc -bam ../bams/IonXpress_091_rawlib.bam -outdir ../coverage_et_qual/091
$QUALIMAP bamqc -bam ../bams/IonXpress_092_rawlib.bam -outdir ../coverage_et_qual/092
$QUALIMAP bamqc -bam ../bams/IonXpress_093_rawlib.bam -outdir ../coverage_et_qual/093
$QUALIMAP bamqc -bam ../bams/IonXpress_094_rawlib.bam -outdir ../coverage_et_qual/094
$QUALIMAP bamqc -bam ../bams/IonXpress_095_rawlib.bam -outdir ../coverage_et_qual/095
$QUALIMAP bamqc -bam ../bams/IonXpress_096_rawlib.bam -outdir ../coverage_et_qual/096
