file_list = ['001.vcf.gz',
             '002.vcf.gz',
             '003.vcf.gz',
             '004.vcf.gz',
             '005.vcf.gz',
             '006.vcf.gz',
             '007.vcf.gz',
             '008.vcf.gz',
             '009.vcf.gz',
             '010.vcf.gz',
             '011.vcf.gz',
             '012.vcf.gz',
             '013.vcf.gz',
             '014.vcf.gz',
             '015.vcf.gz',
             '016.vcf.gz',
             '017.vcf.gz',
             '018.vcf.gz',
             '019.vcf.gz',
             '020.vcf.gz',
             '021.vcf.gz',
             '022.vcf.gz',
             '023.vcf.gz',
             '024.vcf.gz',
             '025.vcf.gz',
             '026.vcf.gz',
             '027.vcf.gz',
             '028.vcf.gz',
             '029.vcf.gz',
             '030.vcf.gz',
             '031.vcf.gz',
             '032.vcf.gz',
             '033.vcf.gz',
             '034.vcf.gz',
             '035.vcf.gz',
             '036.vcf.gz',
             '037.vcf.gz',
             '038.vcf.gz',
             '039.vcf.gz',
             '040.vcf.gz',
             '041.vcf.gz',
             '042.vcf.gz',
             '043.vcf.gz',
             '044.vcf.gz',
             '045.vcf.gz',
             '046.vcf.gz',
             '047.vcf.gz',
             '048.vcf.gz',
             '049.vcf.gz',
             '050.vcf.gz',
             '051.vcf.gz',
             '052.vcf.gz',
             '053.vcf.gz',
             '054.vcf.gz',
             '055.vcf.gz',
             '056.vcf.gz',
             '057.vcf.gz',
             '058.vcf.gz',
             '059.vcf.gz',
             '060.vcf.gz',
             '061.vcf.gz',
             '062.vcf.gz',
             '063.vcf.gz',
             '064.vcf.gz',
             '065.vcf.gz',
             '066.vcf.gz',
             '067.vcf.gz',
             '068.vcf.gz',
             '069.vcf.gz',
             '070.vcf.gz',
             '071.vcf.gz',
             '072.vcf.gz',
             '073.vcf.gz',
             '074.vcf.gz',
             '075.vcf.gz',
             '076.vcf.gz',
             '077.vcf.gz',
             '078.vcf.gz',
             '079.vcf.gz',
             '080.vcf.gz',
             '081.vcf.gz',
             '082.vcf.gz',
             '083.vcf.gz',
             '084.vcf.gz',
             '085.vcf.gz',
             '086.vcf.gz',
             '087.vcf.gz',
             '088.vcf.gz',
             '089.vcf.gz',
             '090.vcf.gz',
             '091.vcf.gz',
             '092.vcf.gz',
             '093.vcf.gz',
             '094.vcf.gz',
             '095.vcf.gz',
             '096.vcf.gz', ]
json_list = ['../vep/001_list.json',
             '../vep/002_list.json',
             '../vep/003_list.json',
             '../vep/004_list.json',
             '../vep/005_list.json',
             '../vep/006_list.json',
             '../vep/007_list.json',
             '../vep/008_list.json',
             '../vep/009_list.json',
             '../vep/010_list.json',
             '../vep/011_list.json',
             '../vep/012_list.json',
             '../vep/013_list.json',
             '../vep/014_list.json',
             '../vep/015_list.json',
             '../vep/016_list.json',
             '../vep/017_list.json',
             '../vep/018_list.json',
             '../vep/019_list.json',
             '../vep/020_list.json',
             '../vep/021_list.json',
             '../vep/022_list.json',
             '../vep/023_list.json',
             '../vep/024_list.json',
             '../vep/025_list.json',
             '../vep/026_list.json',
             '../vep/027_list.json',
             '../vep/028_list.json',
             '../vep/029_list.json',
             '../vep/030_list.json',
             '../vep/031_list.json',
             '../vep/032_list.json',
             '../vep/033_list.json',
             '../vep/034_list.json',
             '../vep/035_list.json',
             '../vep/036_list.json',
             '../vep/037_list.json',
             '../vep/038_list.json',
             '../vep/039_list.json',
             '../vep/040_list.json',
             '../vep/041_list.json',
             '../vep/042_list.json',
             '../vep/043_list.json',
             '../vep/044_list.json',
             '../vep/045_list.json',
             '../vep/046_list.json',
             '../vep/047_list.json',
             '../vep/048_list.json',
             '../vep/049_list.json',
             '../vep/050_list.json',
             '../vep/051_list.json',
             '../vep/052_list.json',
             '../vep/053_list.json',
             '../vep/054_list.json',
             '../vep/055_list.json',
             '../vep/056_list.json',
             '../vep/057_list.json',
             '../vep/058_list.json',
             '../vep/059_list.json',
             '../vep/060_list.json',
             '../vep/061_list.json',
             '../vep/062_list.json',
             '../vep/063_list.json',
             '../vep/064_list.json',
             '../vep/065_list.json',
             '../vep/066_list.json',
             '../vep/067_list.json',
             '../vep/068_list.json',
             '../vep/069_list.json',
             '../vep/070_list.json',
             '../vep/071_list.json',
             '../vep/072_list.json',
             '../vep/073_list.json',
             '../vep/074_list.json',
             '../vep/075_list.json',
             '../vep/076_list.json',
             '../vep/077_list.json',
             '../vep/078_list.json',
             '../vep/079_list.json',
             '../vep/080_list.json',
             '../vep/081_list.json',
             '../vep/082_list.json',
             '../vep/083_list.json',
             '../vep/084_list.json',
             '../vep/085_list.json',
             '../vep/086_list.json',
             '../vep/087_list.json',
             '../vep/088_list.json',
             '../vep/089_list.json',
             '../vep/090_list.json',
             '../vep/091_list.json',
             '../vep/092_list.json',
             '../vep/093_list.json',
             '../vep/094_list.json',
             '../vep/095_list.json',
             '../vep/096_list.json',]

etnia = {
    '1': 'Tzotzil',
    '2': 'Chontal_Tab',
    '3': 'Huave',
    '4': 'Cucapa',
    '5': 'Zapoteco',
    '6': 'Maya',
    '7': 'Matlaltzinca',
    '8': 'Tzeltal',
    '9': 'Tzeltal',
    '10': 'Pame',
    '11': 'Nahuatl',
    '12': 'Lacandon',
    '13': 'Tzotzil',
    '14': 'Chontal_Tab',
    '15': 'Tzotzil',
    '16': 'Mixteco',
    '17': 'Tzeltal',
    '18': 'Seri',
    '19': 'Maya',
    '20': 'Popoluca_Sierra',
    '21': 'Zapoteco',
    '22': 'Amuzgo',
    '23': 'Zoque',
    '24': 'Kekchi',
    '25': 'Purepecha',
    '26': 'Chatino',
    '27': 'Zoque',
    '28': 'Chol',
    '29': 'Tzeltal',
    '30': 'Tzeltal',
    '31': 'Chol',
    '32': 'Otomi',
    '33': 'Kiliwa',
    '34': 'Tzotzil',
    '35': 'Mixteco',
    '36': 'Huichol',
    '37': 'Poptijacalteco',
    '38': 'Poptijacalteco',
    '39': 'Tzotzil',
    '40': 'Mame',
    '41': 'Mame',
    '42': 'Kanjobal',
    '43': 'Kanjobal',
    '44': 'Tojolabal',
    '45': 'Tojolabal',
    '46': 'Tojolabal',
    '47': 'Tojolabal',
    '48': 'Tojolabal',
    '49': 'Tarahumara',
    '50': 'Tarahumara',
    '51': 'Tarahumara',
    '52': 'Tarahumara',
    '53': 'Tarahumara',
    '54': 'Tarahumara',
    '55': 'Cora',
    '56': 'Chol',
    '57': 'Seri',
    '58': 'Seri',
    '59': 'ND',
    '60': 'ND',
    '61': 'Mazateco',
    '62': 'Mazateco',
    '63': 'Mazateco',
    '64': 'Mazateco',
    '65': 'Yaqui',
    '66': 'Yaqui',
    '67': 'Yaqui',
    '68': 'Yaqui',
    '69': 'Yaqui',
    '70': 'Yaqui',
    '71': 'Nahuatl',
    '72': 'Otomi',
    '73': 'Otomi',
    '74': 'Zoque',
    '75': 'Chinanteco',
    '76': 'Totonaco',
    '77': 'Chinanteco',
    '78': 'Chinanteco',
    '79': 'Zoque',
    '80': 'Chinanteco',
    '81': 'ND',
    '82': 'Zoque',
    '83': 'Popoluca_Sierra',
    '84': 'Popoluca_Sierra',
    '85': 'Popoluca_Sierra',
    '86': 'Popoluca_Sierra',
    '87': 'Popoluca_Sierra',
    '88': 'Totonaco',
    '89': 'Totonaco',
    '90': 'Totonaco',
    '91': 'Totonaco',
    '92': 'Pame',
    '93': 'Pame',
    '94': 'Pame',
    '95': 'Huasteco',
    '96': 'Huasteco',
    '97': 'Nahuatl',
    '98': 'Huasteco',
    '99': 'Huasteco',
    '100': 'Nahuatl',
    '101': 'ND',
    '102': 'Mixe',
    '103': 'Mixe',
    '104': 'Mixe',
    '105': 'Zoque',
    '106': 'Mixe',
    '107': 'Maya',
    '108': 'Maya',
    '109': 'Mazahua',
    '110': 'Mazahua',
    '111': 'Zapoteco',
    '112': 'Sin_Etnia',
    '113': 'Mazahua',
    '114': 'Mexicano',
    '115': 'Zapoteco',
    '116': 'Mexicano',
    '117': 'Mexicano',
    '118': 'Mexicano',
    '119': 'Mazahua',
    '120': 'Mazateco',
    '121': 'Chontal_Oax',
    '122': 'Purepecha',
    '123': 'Nahuatl',
    '124': 'Purepecha',
    '125': 'Otomi',
    '126': 'Zapoteco',
}
