VEP=~/Downloads/ensembl-tools-release-76/scripts/variant_effect_predictor/variant_effect_predictor.pl

$VEP --everything -i /home/rgarcia/mt/vcfs/001.vcf.gz -o ../vep/001.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/002.vcf.gz -o ../vep/002.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/003.vcf.gz -o ../vep/003.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/004.vcf.gz -o ../vep/004.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/005.vcf.gz -o ../vep/005.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/006.vcf.gz -o ../vep/006.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/007.vcf.gz -o ../vep/007.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/008.vcf.gz -o ../vep/008.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/009.vcf.gz -o ../vep/009.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/010.vcf.gz -o ../vep/010.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/011.vcf.gz -o ../vep/011.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/012.vcf.gz -o ../vep/012.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/013.vcf.gz -o ../vep/013.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/014.vcf.gz -o ../vep/014.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/015.vcf.gz -o ../vep/015.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/016.vcf.gz -o ../vep/016.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/017.vcf.gz -o ../vep/017.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/018.vcf.gz -o ../vep/018.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/019.vcf.gz -o ../vep/019.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/020.vcf.gz -o ../vep/020.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/021.vcf.gz -o ../vep/021.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/022.vcf.gz -o ../vep/022.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/023.vcf.gz -o ../vep/023.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/024.vcf.gz -o ../vep/024.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/025.vcf.gz -o ../vep/025.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/026.vcf.gz -o ../vep/026.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/027.vcf.gz -o ../vep/027.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/028.vcf.gz -o ../vep/028.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/029.vcf.gz -o ../vep/029.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/030.vcf.gz -o ../vep/030.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/031.vcf.gz -o ../vep/031.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/032.vcf.gz -o ../vep/032.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/033.vcf.gz -o ../vep/033.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/034.vcf.gz -o ../vep/034.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/035.vcf.gz -o ../vep/035.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/036.vcf.gz -o ../vep/036.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/037.vcf.gz -o ../vep/037.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/038.vcf.gz -o ../vep/038.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/039.vcf.gz -o ../vep/039.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/040.vcf.gz -o ../vep/040.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/041.vcf.gz -o ../vep/041.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/042.vcf.gz -o ../vep/042.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/043.vcf.gz -o ../vep/043.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/044.vcf.gz -o ../vep/044.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/045.vcf.gz -o ../vep/045.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/046.vcf.gz -o ../vep/046.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/047.vcf.gz -o ../vep/047.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/048.vcf.gz -o ../vep/048.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/049.vcf.gz -o ../vep/049.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/050.vcf.gz -o ../vep/050.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/051.vcf.gz -o ../vep/051.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/052.vcf.gz -o ../vep/052.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/053.vcf.gz -o ../vep/053.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/054.vcf.gz -o ../vep/054.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/055.vcf.gz -o ../vep/055.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/056.vcf.gz -o ../vep/056.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/057.vcf.gz -o ../vep/057.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/058.vcf.gz -o ../vep/058.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/059.vcf.gz -o ../vep/059.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/060.vcf.gz -o ../vep/060.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/061.vcf.gz -o ../vep/061.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/062.vcf.gz -o ../vep/062.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/063.vcf.gz -o ../vep/063.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/064.vcf.gz -o ../vep/064.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/065.vcf.gz -o ../vep/065.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/066.vcf.gz -o ../vep/066.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/067.vcf.gz -o ../vep/067.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/068.vcf.gz -o ../vep/068.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/069.vcf.gz -o ../vep/069.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/070.vcf.gz -o ../vep/070.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/071.vcf.gz -o ../vep/071.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/072.vcf.gz -o ../vep/072.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/073.vcf.gz -o ../vep/073.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/074.vcf.gz -o ../vep/074.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/075.vcf.gz -o ../vep/075.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/076.vcf.gz -o ../vep/076.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/077.vcf.gz -o ../vep/077.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/078.vcf.gz -o ../vep/078.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/079.vcf.gz -o ../vep/079.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/080.vcf.gz -o ../vep/080.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/081.vcf.gz -o ../vep/081.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/082.vcf.gz -o ../vep/082.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/083.vcf.gz -o ../vep/083.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/084.vcf.gz -o ../vep/084.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/085.vcf.gz -o ../vep/085.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/086.vcf.gz -o ../vep/086.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/087.vcf.gz -o ../vep/087.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/088.vcf.gz -o ../vep/088.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/089.vcf.gz -o ../vep/089.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/090.vcf.gz -o ../vep/090.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/091.vcf.gz -o ../vep/091.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/092.vcf.gz -o ../vep/092.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/093.vcf.gz -o ../vep/093.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/094.vcf.gz -o ../vep/094.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/095.vcf.gz -o ../vep/095.tsv --fork 6 --offline --assembly GRCh37
$VEP --everything -i /home/rgarcia/mt/vcfs/096.vcf.gz -o ../vep/096.tsv --fork 6 --offline --assembly GRCh37
